### ISSUE TITLE
Time to 20 Percent

### ISSUE THREAD

**Issue by ChristoffBo** [Danie10/gadgeteerza-homeassistant#2]
Hi Danie,

Perhaps you can help, i want to also create a template sensor to calculate when my batteries will reach 20 percent or ëmpty.

I have the following installed:

5x Hubble am2 batteries.

I use solar assistant to get MQTT messages sent to my homeassistant.

I currently get the following entities:

Battery SOC in percentage - sensor.battery_state_of_Charge

PV Power combined - sensor.pv_power

Combined load in watts - sensor.load_power

battery voltage - sensor.battery_voltage

so my batteries are as follows:

Battery Capacity - 500Ah
Float charge - 53.4V
To grid - 47.0V
Shutdown voltage 44.0V

how on earth will i create a template as you have for tome to 0?

**Comment by Danie10** [comment]
Hi there, OK if you get a percentage SOC back that is quite useful. My code did spell out the algorithm I was using so not sure if you looked at that? I was basically doing a live calculation on difference in SOC ie. if it is at 80% now and I want to calculate time to 20% then difference is 60%.

Other factor is power in Watts is volts * amps so if you know the Watts (Power) and you know volts, then you can calculate Amps at any point in time (current load).  But I think I was working off the total capacity of my battery. So if yours is 500Ah then 10A load will last 50 hours to empty (assuming it is a LiFeO4 type battery that runs to 0%).

Watts at 48V is the same as Watts at 220V. So if something draws 1A at 220V = 220W. At 48V the current will be 4.58A draw on battery.

So to come back to the example, if you want to calculate the run time from 80% (current SOC) down to 20% (target) which is 60% diff. You are looking at using 60% of 500 Ah which is 300 Ah. So the time to go should be 300 / Amps currently drawn = 300 / 10 A (example) = 30 hours. As the current varies so will the time to go. Time to 0% would just be an extra 20% of 500 Ah.

Hope that is right as I tend to test it by trial and error to check it makes sense when in use.

**Comment by ChristoffBo** [comment]
Ok, cool, no idea what you just said goes over my head.

I tried to copy your template into development on HA as well but it says the float is incorrect.

will keep searching for a template.

thank you

**Comment by Danie10** [comment]
OK best is to look at how I defined it in the sensors config file at [](https://github.com/Danie10/gadgeteerza-homeassistant/blob/main/ha-configs/sensors.yaml).

There is a place under dev tools in Home Assistant where you can paste a template in to test and tweak it. I sat there for a good day or two days getting the syntax etc right until I arrived at the working template as per linked file above.

Yes, if you got a float error it may be that something is defined (or defaults to an integer or text type value. It needs to have matching types to work a calculation.
